# This rule is not used by the project doris-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to doris.kubedoop.dev.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: doris-operator
    app.kubernetes.io/managed-by: kustomize
  name: doriscluster-viewer-role
rules:
- apiGroups:
  - doris.kubedoop.dev
  resources:
  - dorisclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - doris.kubedoop.dev
  resources:
  - dorisclusters/status
  verbs:
  - get
